apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: second-fast-apipython3
  name: second-fast-apipython3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: second-fast-apipython3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: second-fast-apipython3
    spec:
      containers:
      - image: parimalppatil/second-fast-apipython3:v3
        imagePullPolicy: IfNotPresent
        name: python3-fastapi
      restartPolicy: Always 

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fast-apipython3
  name: fast-apipython3
spec:
  # clusterIP: 10.12.6.111
  # clusterIPs:
  # - 10.12.6.111
  # externalTrafficPolicy: Cluster
  # ipFamilies:
  # - IPv4
  # ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30600
    port: 5151
    protocol: TCP
    targetPort: 5151
  selector:
    app: second-fast-apipython3
  sessionAffinity: None
  type: LoadBalancer
# status:
#   loadBalancer:
#     ingress:
#     - ip: 34.71.143.182
